############################################
# AMBIENTE PARA N8N CLOUD + WAHA + REDIS
############################################
# Criado por Gabriel Henrique
# Baseado no setup de Guilherme Lazarotto
# Adaptado para integração com N8N Cloud Starter
############################################

services:
  ##########################################
  # REDIS - memória do agente de IA
  ##########################################
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass default
    environment:
      REDIS_PASSWORD: default
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ##########################################
  # WAHA - WhatsApp API Headless
  ##########################################
  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      # 👉 Substitua abaixo pela URL do seu webhook N8N Cloud:
      # Exemplo: https://seuusuario.n8n.cloud/webhook/webhook
      WHATSAPP_HOOK_URL: https://SEU_SUBDOMINIO_DO_N8N.n8n.cloud/webhook/webhook

      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true

    ports:
      - "3000:3000"  # Painel WAHA
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media

volumes:
  waha_sessions:
  waha_media:
  redis_data:
